version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'nethermind'
        ETHEREUM_JSONRPC_HTTP_URL: https://rpc.eiob.xyz/
        ETHEREUM_JSONRPC_HTTP_INSECURE: 'true'
        ETHEREUM_JSONRPC_PENDING_TRANSACTIONS_TYPE: 'parity'
        CHAIN_ID: '612'
        COIN: 'EIOB'
        COIN_NAME: 'EIOB'
        RE_CAPTCHA_DISABLED: 'true'

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    environment:
      NEXT_PUBLIC_NETWORK_ID: '612'
      NEXT_PUBLIC_NETWORK_RPC_URL: https://rpc.eiob.xyz/
      NEXT_PUBLIC_NETWORK_NAME: 'EIOB MAINNET'
      NEXT_PUBLIC_NETWORK_SHORT_NAME: 'EIOB'
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: 'EIOB'
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: 'EIOB'
      NEXT_PUBLIC_AD_BANNER_PROVIDER: 'none'
      NEXT_PUBLIC_AD_TEXT_PROVIDER: 'none'
      NEXT_PUBLIC_IS_TESTNET: 'false'

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
